sudo: required
services:
  - docker

before_install:
  - docker build -t cdifranco1/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true cdifranco1/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-839863774597"
  bucket_path: "docker-react"
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
  on:
    branch: master